name: Build

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [base-image-update]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Output Rebuild Info
        if: ${{ github.event.client_payload }}
        shell: pwsh
        run: |
          $updates = '${{ toJson(github.event.client_payload.updates) }}' | ConvertFrom-Json
          foreach ($update in $updates) {
            echo "Rebuilding $($update.targetImageName) to be in sync with $($update.baseImageName)"
          }

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      
      # Push another version of the image which has a label
      - name: Build and push Docker image
        id: build-and-push-base-label
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-label
          labels: org.opencontainers.image.base.name=alpine:latest
      - name: Build and push Docker image
        id: build-and-push-base-label-diff
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-label-diff
          labels: org.opencontainers.image.base.name=alpine:3.18

      # Push another version of the image which has an annotation
      - name: Build and push Docker image
        id: build-and-push-base-annotation
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-annotation
          annotations: org.opencontainers.image.base.name=alpine:latest
      - name: Build and push Docker image
        id: build-and-push-base-annotation-diff
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-annotation-diff
          annotations: org.opencontainers.image.base.name=alpine:3.18
