name: Monitor (Dockerfile, base stage name)

on:
  schedule:
  # At midnight on Tuesdays
  - cron: "0 0 * * 2"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mthalman/docker-bump-action@v0
        with:
          target-image-name: ghcr.io/mthalman/docker-bump-action-example:latest
          dockerfile: Dockerfile
          base-stage-name: base
